name: OT2_ADT
channels:
  - conda-forge
dependencies:
  - h5py
  - imageio
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - matplotlib
  - nose
  - notebook
  - numpy
  - opentrons
  - pandas
  - python
  - scipy
  - sphinx
  - tabulate
